spring:
  webflux:
    hiddenmethod:
      filter:
        enable: true
#   data:
#     mongodb:
#       host: 127.0.0.1
#       port: 27017

# # mongodb
# mongodb:
#   test:
#     connectionString: mongodb://localhost:27017/test

