spring:
  webflux:
    hiddenmethod:
      filter:
        enable: true
  mongodb:
    embedded:
      version: 3.4.5 # 4.0.21
  output:
    ansi:
      enabled: ALWAYS
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test

mongodb:
  test:
    connectionString: mongodb://localhost:27017/test

